### ISSUE TITLE
Ask IOL #1 fellows to share updates via blog posts on OPN / CC website

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#10]
Send note to ALL IOL #1 fellows:
    - checking in
    - Ask IOL #1 fellows to share updates via blog posts on OPN / CC website

**Comment by cablegreen** [comment]
Send note to ALL IOL #1 fellows:
- checking in
- Ask IOL #1 fellows to share updates via blog posts on OPN / CC website

**Comment by cablegreen** [comment]
Note sent to mentors and fellows multiple times - no response

**Comment by cablegreen** [comment]
I asked 2-3 times ... no response.  Tim - do you want to try?  ;)   If not success - then let's close it and move on.

**Comment by tvol** [comment]
@tvol reping klaudia to post hers and use it to prompt the rest of the fellows too
