### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/Institute-for-Open-Leadership#14]
Add to IOL internal master:

https://docs.google.com/a/creativecommons.org/document/d/1wIygIhZ5egVhsIlZ1MELT2HhGBgIhnkZ4gaLNRNkAE8/edit

**Comment by tvol** [comment]
revised timeline: July 10, 2015 (cable)

August 7, 2015 - application window opened
September 8, 2015 - application window closed
September 22 - fellows selected
October 12 - fellows respond
October 19 - public announcement of fellows
December 15 - reading materials & agenda distributed to fellows
January 7 - intro webinar for round 2 fellows

**Comment by cablegreen** [comment]
looks good to me

**Comment by cablegreen** [comment]
revised timeline: Sept 16, 2015 (cable)

September 28, 2015 - application window opened: mentors and fellows
October 30, 2015 - application window closed: mentors and fellows
November 13 - mentors and fellows selected
November 30 - mentors and fellows deadline to accept
December 4 - public announcement of fellows
December 14 - reading materials & agenda distributed to fellows
January 7 - intro webinar for round 2 fellows

**Comment by cablegreen** [comment]
revised timeline: Nov 14, 2015 (cable)

November 17 - mentors and fellows selected
November 30 - mentors and fellows deadline to accept
December 4 - public announcement of fellows
December 14 - reading materials & agenda distributed to fellows
January 7 - intro webinar for round 2 fellows

**Comment by tvol** [comment]
* send note to nicole thread
* send note to applicants about timing
* Cable will review rest of A
* tvol will review rest of B
* cable/tvol meeting thurs noon for decisions
* send notes to cc-staff, review committee, kelsey, klaudia about top candidates
* friday afternoon send to winning candidates and placeholder for losing candidates

**Comment by cablegreen** [comment]
revised timeline: Nov 25, 2015 (cable)

November 25 - mentors and fellows selected
November 30-ish - mentors and fellows deadline to accept
December 4 - public announcement of fellows (IOL web site)
December 18 - reading materials & agenda distributed to fellows
January 7-ish - intro webinar for round 2 fellows

# 

Next steps:

```
I will create a draft IOL2 agenda... and will share it with you all for feedback in the coming weeks.
Kelsey is working on logistics (hotel, food, transportation, meeting spaces, ice breaker events, etc)
November 30-ish - mentors and fellows deadline to accept ... Cable & Tim will confirm with all
December 4-ish - public announcement of fellows (IOL web site)
Late December / early January - IOL2 agenda distributed to fellows (after it is approved by this group)
January - intro webinar for round 2 fellows
```

**Comment by tvol** [comment]
@cablegreen all invited fellows have now confirmed.

**Comment by cablegreen** [comment]
moved remaining timeline items to master agenda: https://docs.google.com/document/d/1SoUFP54aQ0bgzW1QSSdz9dWZPd42NelBMbULC_a_aGU/edit
