### ISSUE TITLE
Create Advisory Committee for IOL #2 

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/Institute-for-Open-Leadership#16]
Advisory Committee for IOL #2? - OPN volunteers?
- raised on OPN call (if interested - contact Tim and Cable) - done
- TVOL send quick email to steering committee that we want to setup IOL advisory committee for next time around - done  (thread: [OPN Steering] IOL Advisory Committee for round 2)
- selecting mentors (Tim+ Cable + regional experts)
- selecting fellows
- selecting location
- lessons learned / feedback ... adjust agenda for IOL #2

**Comment by tvol** [comment]
@cablegreen is checking whether bekka wants to join, and will send a reminder email to the OPN Google Group

**Comment by cablegreen** [comment]
reminder sent to OPN group - thread: IOL #2: Advisory Committee - join?

YES:

Teri Karobonik
Staff Attorney--New Media Rights
p:619-591-8870

**Comment by cablegreen** [comment]
The IOL #2 Advisory Committee consists of the following OPN members:

Teri Karobonik

teri@newmediarights.org

Iryna Kuchma

iryna.kuchma@eifl.net

Rebecca Kahn

bekka.kahn@gmail.com

Igor Lesko

igorlesko@oeconsortium.org

David Ernst

dernst@umn.edu

Alek Tarkowski

atarkowski@centrumcyfrowe.pl

Cable Green

cable@creativecommons.org

Tim Vollmer

tvol@creativecommons.org

Our committee will keep the OPN Steering Committee and the full OPN membership updated as planning for the second "Institute for Open Leadership" moves forward.
