### ISSUE TITLE
update IOL2 application text for the OPN website

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#22]
https://openpolicynetwork.org/iol/

From feedback from round 1, Give better context for what _is_ policy (be clear in application process and screen for this), and how it is different than programs/practice.

**Comment by tvol** [comment]
need to clarify IOL will be conducted in English

**Comment by tvol** [comment]
Make it clear to fellows how their applications will be used and shared

**Comment by cablegreen** [comment]
Cable reviewed - good to go - share with advisory committee

draft post looks great too:  https://docs.google.com/document/d/1iFZtgf7WiEHCiTKepcfBaRiHGEFY1iogC9lw_B0RbaA/edit?usp=sharing

**Comment by tvol** [comment]
Shared both with advisory committee. will entertain feedback until COB 25 September.

**Comment by tvol** [comment]
done
