### ISSUE TITLE
Work with IOL #2 Mentors

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#23]
- need better representation of all subject areas, including GLAM
- need better gender balance
- need better geographic diversity

**Comment by cablegreen** [comment]
Mentors: need 2 more
(1) CC: Cable, Tim
(2) David Ernst (Open Textbooks Network)
(3) still need: 
    need better representation: open science, GLAM, open data, open access (ask Tobias and Kelsey to help find mentors)
    need better gender balance
    need better geographic diversity

Fellows: 14 + Vincent
(1) put out call for fellows
(2) HOLD spot for Vincent Kizza

Facilitator: 
Paul Stacey + Kelsey (and open biz models)

**Comment by cablegreen** [comment]
+ Kelsey for mentor

**Comment by cablegreen** [comment]
Check with Nicole - come on her own budget ...  (1) lead webinar on campaign in advance? (2) coming to Cape Town?

**Comment by cablegreen** [comment]
mentors: Kelsey, Dave, Tim, Cable, Klaudia (5)
facilitator: Paul (1) & Kelsey 

6 total ... leaves space / budget for 14-15 fellows (Vincent Kizza is already admitted)

**Comment by cablegreen** [comment]
Nov 12 meeting notes: https://docs.google.com/document/d/1ZRcECHNDFoShqMrJjIZ5SQW0y5zxdcDzuHwC8MDaeo0/edit

**Comment by cablegreen** [comment]
thread to Vincent: Very urgent- Flight aborting

Vincent confirmed - he's in.

**Comment by cablegreen** [comment]
Mentors finalized:
Kelsey Weins, Klaudia Grabowska, David Ernst, Tim Vollmer, Paul Stacey, Cable Green

**Comment by cablegreen** [comment]
IOL review sheet

**Comment by cablegreen** [comment]
acceptance /rejection letter: https://docs.google.com/document/d/1BsC709GfNBpoeAUpMxPIvPS4Fngb2pf81isNeNcPoFs/edit

**Comment by cablegreen** [comment]
moved to the master agenda: https://docs.google.com/document/d/1SoUFP54aQ0bgzW1QSSdz9dWZPd42NelBMbULC_a_aGU/edit
