### ISSUE TITLE
Fellow application reviews by advisory committee

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#31]
@cablegreen due 11 November end of day

**Comment by cablegreen** [comment]
Confirmed. 

Cable

**Comment by cablegreen** [comment]
Hi Tim: Do you want to nudge everyone - give them a final deadline of Monday - and let them know you and I will be meeting on Nov 17 to make final decisions and alert IOL applicants?

**Comment by cablegreen** [comment]
Sent Nov 16, 2015 - to IOL Adv Committee

Greetings Friends:

Tim and I met today ... we're running 1 week behind schedule and IOL #2 candidates are starting to e-mail us asking when they will be notified.

We need to wrap up the IOL #2 application reviews and move forward.

Four of us have not yet completed reviews... I think all of these fine folks are busy at OpenCon in Brussels. Totally understandable.

If you still want / have time to complete your reviews - please do so no later than tomorrow, November 11: 10:00am pacific / 7:00pm Brussels time (GMT +1).

After that, Tim and I will divide and complete the rest of the application reviews. 

Next steps:

```
Tim and I are going to meeting Nov 11 at 2:00pm to review all of the scores and make an initial selection of the 14 IOL #2 fellows. 
We will send that list to this team for quick feedback.
We'll adjust their travel budgets (removing food and hotel costs in South Africa ... as we will cover those expenses locally) - and make a final decision re: how many IOL #2 fellows we can take and stay within budget.
    Our goal is to accept 15 total fellows (including Vincent Kizza who is already admitted).
Tim will then send offer letters (with the revised budgets) to the IOL #2 fellows - and give them a short window to accept.
If some drop out - we'll fill in with alternates.
```

Gratefully,

Cable

**Comment by cablegreen** [comment]
Review sheet: https://docs.google.com/spreadsheets/d/1WkU8vhmdsY7ZRzdKoMFaJQMViIp5gS26Vp188Ec8lF0/edit#gid=297938700&vpid=A2

**Comment by cablegreen** [comment]
Done - closing issue.
