### ISSUE TITLE
send intro email to IOL2 fellows

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#34]
to include via the IOL2 google group:
- location of hotel
- link to generic visa letter
- info about insurance and medical
- ask them to tell us about food restrictions now
- ask them to introduce themselves on the list
- note that we're going to do a blog post on Thursday, Dec 3
- info about the open textbook summit

**Comment by tvol** [comment]
@cablegreen is this everything?

**Comment by cablegreen** [comment]
Yep - I think that should cover it.

**Comment by tvol** [comment]
sent Tues, Dec 1
