### ISSUE TITLE
Check in with Puneet - mentor fellows?

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/Institute-for-Open-Leadership#5]

**Comment by cablegreen** [comment]
Puneet - still with his fellows? need to confirm - or move his fellows to Tim and Cable

**Comment by tvol** [comment]
@cablegreen I thought he said he would do it?

**Comment by cablegreen** [comment]
He said he wanted to think about it - and would get back to us. We need to loop back and check with him, I think.

**Comment by cablegreen** [comment]
Puneet confirmed - he is in for the remainder of IOL #1
