### ISSUE TITLE
List IOL #2 communication next steps

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/Institute-for-Open-Leadership#8]
#2: Advertise IOL #2 through OPN and other channels #8 

CC blog post - template @ https://creativecommons.org/weblog/entry/41633

OPN post: https://openpolicynetwork.org/announcing-the-institute-for-open-leadership-fellows/

IOL summary for funders and board: https://docs.google.com/a/creativecommons.org/document/d/1HwnFr9_ksfGAZ4S4EdMiY-yLP5qw6pUw3ZrwsLuaDAk/edit

Update Comms plan on internal master: https://docs.google.com/a/creativecommons.org/document/d/1wIygIhZ5egVhsIlZ1MELT2HhGBgIhnkZ4gaLNRNkAE8/edit

**Comment by cablegreen** [comment]
List communication next steps (announcing IOL #2, etc.)

**Comment by cablegreen** [comment]
CC post draft: https://docs.google.com/document/d/1iFZtgf7WiEHCiTKepcfBaRiHGEFY1iogC9lw_B0RbaA/edit?usp=sharing

**Comment by tvol** [comment]
@cablegreen I will publish blog posts on CC.org and OPN on Monday, 28 September. Will send to OPN list, TJ, Dana, Melissa.

**Comment by tvol** [comment]
done https://creativecommons.org/weblog/entry/46104

**Comment by tvol** [comment]
will do followup push on social media on Oct 12, 26

**Comment by tvol** [comment]
done.
